### 사과 품질 분류하기
* 컬럼
    - Size : 크기
    - Weight : 무게
    - Sweetness : 단맛
    - Crunchiness : 아삭한 정도
    - Juiciness : 사과 즙의 정도
    - Ripeness : 사과의 숙성 정도
    - Acidity : 신맛
    - Quality : 품질

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data_set/4.분류/apple_quality.csv")
df.head()

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good

In [3]:
df['Quality'].unique()

array(['good', 'bad', nan], dtype=object)

In [4]:
df.isnull().sum()

A_id           1
Size           1
Weight         1
Sweetness      1
Crunchiness    1
Juiciness      1
Ripeness       1
Acidity        0
Quality        1
dtype: int64

In [5]:
df.shape

(4001, 9)

In [6]:
df.dropna(axis=0, inplace=True)

In [7]:
df.shape

(4000, 9)

In [8]:
df.isnull().sum()

A_id           0
Size           0
Weight         0
Sweetness      0
Crunchiness    0
Juiciness      0
Ripeness       0
Acidity        0
Quality        0
dtype: int64

In [9]:
df.columns

Index(['A_id', 'Size', 'Weight', 'Sweetness', 'Crunchiness', 'Juiciness',
       'Ripeness', 'Acidity', 'Quality'],
      dtype='object')

In [10]:
df.head(1)

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.34633,-1.012009,1.8449,0.32984,-0.491590483,good

In [14]:
features = ['Size', 'Weight', 'Sweetness', 'Crunchiness', 'Juiciness',
       'Ripeness', 'Acidity']
label = 'Quality'
X, y = df[features], df[label]
X.head(3), y

(       Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness  \
 0 -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840
 1 -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530
 2 -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033

         Acidity
 0  -0.491590483
 1  -0.722809367
 2   2.621636473  ,
 0       good
 1       good
 2        bad
 3       good
 4       good
         ...
 3995     bad
 3996    good
 3997     bad
 3998    good
 3999    good
 Name: Quality, Length: 4000, dtype: object)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
# train_test_split: 데이터를 랜덤으로 섞어서 나눔
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # 30%만 테스트용으로 사용

In [18]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2800, 7), (2800,), (1200, 7), (1200,))

### 모델 생성 및 학습, 평가

#### Kneighbors(K-최근접 이웃 알고리즘)
* 주위의 가장 가까운 다른 데이터를 보고 현재 데이터를 판단
* 기본 비교 개수는 5개로 되어 있다
* 비교 개수를 변경하고자 할 경우 n_neighbors에 값 지정

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [21]:
kn = KNeighborsClassifier() #모델생성
kn.fit(X_train, y_train) #학습
kn.score(X_test, y_test)

0.89

#### SVM(Support Vector Machine)
* 특정 데이터들을 구분하는 선을 찾고, 이를 기반으로 패턴을 인식하는 방법
* kernel : linear, rbf
* linear : 선형으로 데이터들을 구분지을 수 있는 경우. 즉, 데이터 분포가 균일 적인 경우
* rbf : 선형으로 데이터를 구분지을 수 없는 경우. 즉, 데이터 분포가 복잡한 경우

In [22]:
import sklearn.svm as svm

In [24]:
svm_linear = svm.SVC(kernel='linear') #Svm 분류 모델(분류기)
svm_linear.fit(X_train, y_train)
svm_linear.score(X_test, y_test)

0.7483333333333333

In [25]:
svm_linear = svm.SVC(kernel='rbf')
svm_linear.fit(X_train, y_train)
svm_linear.score(X_test, y_test)

0.8825

### DecisionTree
* 특정 조건에 따라 가지치기 과정을 반복하면서 모델을 생성한다

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt.score(X_test, y_test)

0.8025

### Ensemble(앙상블)
* 여러 개의 분류기(알고리즘)를 생성하고 그 예측을 결합함으로써 보다 정확한 분류기 생성
* 앙상블의 대표 알고리즘은 랜덤포레스트와 그래디언트부스팅이 있다
>
* 앙상블 학습의 유형
    - 보팅(Voting) : 서로 다른 알고리즘을 가진 분류기를 결합하여 사용
    - 배깅(Bagging) : 모두 같은 유형의 알고리즘을 가진 분류기를 결합하여 사용
        * 대표적 알고리즘인 랜덤포레스트가 있다
    - 부스팅(Boosting) : 오류를 개선해 나가면서 학습하는 방식(다른 알고리즘에 비해 시간이 더 걸림)

#### Voting(보팅)
* 하드보팅(Hard Voting) : 다수의 결정에 의해 결과값이 선정된다
* 소프트보팅(Soft Voting) : 결정된 값들의 평균을 구하고 가장 높은 값을 선정
* 일반적으로 하드보팅보다 소프트 보팅이 성능이 좋아 소프트 보팅을 많이 사용한다

In [33]:
svm_rbf = svm.SVC(kernel="rbf", probability=True)
svm_rbf.fit(X_train, y_train)

kn = KNeighborsClassifier()
kn.fit(X_train, y_train)

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [34]:
from sklearn.ensemble import VotingClassifier

In [36]:
vo = VotingClassifier(estimators=[
    ('svc', svm_rbf), ('knn', kn), ('DT', dt) # 사용할 모델 리스트
],voting='soft') # 확률 기반 투표

In [37]:
vo.fit(X_train, y_train)
print("vo : ", vo.score(X_test, y_test))
print("svm_rbf : ", svm_rbf.score(X_test, y_test))
print("kn : ", kn.score(X_test, y_test))
print("dt : ", dt.score(X_test, y_test))

vo :  0.8891666666666667
svm_rbf :  0.8825
kn :  0.89
dt :  0.7991666666666667

#### RandomForest(랜덤포레스트)
* decision tree 알고리즘을 여러 개의 분류기로 만들어서 보팅(소프트보팅)으로 최종 결정한다

In [38]:
from sklearn.ensemble import RandomForestClassifier

In [41]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
rfc.score(X_test, y_test)

0.8758333333333334

#### 부스팅(Boosting)
* GBM(Gradient Boosting Machine)
    - decision tree를 묶어 강력한 model을 만드는 ensemble기법입니다.
    - 순차적으로 학습-예측하면서 잘못 예측한 데이터의 오류를 개선해 나가면서 학습하는 방법
    - 다른 알고리즘에 비해 처리속도가 느림

In [42]:
from sklearn.ensemble import GradientBoostingClassifier

In [43]:
gbc = GradientBoostingClassifier()
gbc.fit(X_train, y_train)
gbc.score(X_test, y_test)

#fit 학습 : 모델 알고 데이터는 X_train, y_train

0.8441666666666666

### 예측

In [45]:
X_test.head(3)

,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity
530,1.843439,-1.801133,3.093699,0.869797,-1.241769,-1.456678,0.489432337
3158,0.536355,1.633846,-0.955547,0.810189,-0.366008,-0.840467,2.442705012
24,0.522961,-1.428085,-0.743519,1.786716,-4.207544,-1.825231,-1.430429857

In [44]:
kn.predict(X_test)

array(['bad', 'good', 'bad', ..., 'bad', 'good', 'bad'],
      shape=(1200,), dtype=object)

In [46]:
y_test

530      bad
3158    good
24       bad
2616     bad
2632    good
        ...
3385    good
1491    good
2678     bad
3080    good
390      bad
Name: Quality, Length: 1200, dtype: object

In [50]:
kn.predict([[0.536355,1.633846,-0.955547,0.810189,-0.366008,-0.840467,2.442705012]])

C:\Users\hi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array(['good'], dtype=object)

In [49]:
X_test.head()

,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity
530,1.843439,-1.801133,3.093699,0.869797,-1.241769,-1.456678,0.489432337
3158,0.536355,1.633846,-0.955547,0.810189,-0.366008,-0.840467,2.442705012
24,0.522961,-1.428085,-0.743519,1.786716,-4.207544,-1.825231,-1.430429857
2616,0.061757,-0.803276,-1.585623,-1.017087,1.668464,-1.021758,2.342807242
2632,2.873902,-4.183853,1.027657,-1.754543,3.412153,-0.253324,3.206656298